[package]
name = "home_storage_vulkan"
version = "0.1.0"
edition = "2024"
build = "build/build.rs"

[lib]
name = "main"
crate-type = ["cdylib"]

[profile.release]
codegen-units = 1
lto = "fat"
debug-assertions = false
overflow-checks = false
panic = "abort"

[dependencies]
iron_oxide = { path = "../iron_oxide", features = ["vulkan"]}
ash = {version = "0.38.0", default-features = false, features = ["debug", "std"]}
png = "0.18.1"
rand = "0.10.0"

[target.'cfg(target_os = "android")'.dependencies]
winit = { version = "0.30.12", features = ["android-game-activity"] }
ndk = "0.9.0"
log = "0.4.29"
android_logger = "0.15.1"

[target.'cfg(target_os = "linux")'.dependencies]
winit = { version = "0.30.12", default-features = false, features = ["rwh_06", "wayland", "wayland-csd-adwaita"] }

[target.'cfg(all(not(target_os = "android"), not(target_os = "linux")))'.dependencies]
winit = { version = "0.30.12" }

[features]
default = ["linked"]
loaded = ["iron_oxide/loaded"]
linked = ["iron_oxide/linked"]

standalone = []
release = []